jobs:
  include:
      # MacOS (OSX) Jobs
    - os: osx
      language: sh
      python: 3.6
      env: PYVER="3.6.10"
      install:
        - eval "$(/usr/libexec/path_helper)"
        - sudo tlmgr install standalone preview doublestroke relsize fundus-calligra wasysym physics dvisvgm.x86_64-darwin dvisvgm rsfs wasy cm-super
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

    - os: osx
      language: sh
      python: 3.7
      env: PYVER="3.7.7"
      install:
        - eval "$(/usr/libexec/path_helper)"
        - sudo tlmgr install standalone preview doublestroke relsize fundus-calligra wasysym physics dvisvgm.x86_64-darwin dvisvgm rsfs wasy cm-super
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

    - os: osx
      language: sh
      python: 3.8
      env: PYVER="3.8.0" # Using Python 3.8.0 due to error with rich
      install:
        - eval "$(/usr/libexec/path_helper)"
        - sudo tlmgr install standalone preview doublestroke relsize fundus-calligra wasysym physics dvisvgm.x86_64-darwin dvisvgm rsfs wasy cm-super
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod +x ./.travis/osx.sh; sh ./.travis/osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then chmod +x ./.travis/linux.sh; sh ./.travis/linux.sh; fi

branches:
  only:
  - master

addons:
  homebrew:
    packages:
    - ffmpeg
    - sox
    casks:
    - basictex
    update: true

notifications:
  email: false
