language: python
matrix:
    include:
        - os: linux
          python: "3.6"

        - os: linux
          python: "3.7"

        - os: linux
          python: "3.8"

        - os: osx
          language: generic
          python: "3.6"
          env: PYVER="3.6.9"

        - os: osx
          language: generic
          python: "3.7"
          env: PYVER="3.7.5"

        - os: osx
          language: generic
          python: "3.8"
          env: PYVER="3.8.0"

os:
  - linux
  - osx

  # Travis does not currently support python builds on windows or macos
  # https://docs.travis-ci.com/user/languages/python/
  # - osx
  # - windows

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest

# branches that trigger Travis builds
branches:
  only:
  - travis-setup
