language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
      # Linux Jobs
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
    - os: linux
      language: python
      python: 3.8

      # MacOS (OSX) Jobs
    - os: osx
      language: sh
      python: 3.6
      env: PYVER="3.6.10"
    - os: osx
      language: sh
      python: 3.7
      env: PYVER="3.7.7"
    - os: osx
      language: sh
      python: 3.8
      env: PYVER="3.8.0"

      # Windows Jobs
    - os: windows
      language: sh
      python: 3.6
      # the latest version available on chocolatey is 3.6.8
      env: PYVER="3.6.8" PYDIR="Python36"
    - os: windows
      language: sh
      python: 3.7
      env: PYVER="3.7.7" PYDIR="Python37"
    - os: windows
      language: sh
      python: 3.8
      env: PYVER="3.8.0" PYDIR="Python38"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod +x ./.travis/osx.sh; sh ./.travis/osx.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then chmod +x ./.travis/windows.sh; sh ./.travis/windows.sh; fi

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install .

script:
  - pytest

branches:
  only:
  - travis-setup
