jobs:
  include:
      # Linux Jobs
    - os: linux
      language: python
      python: 3.6
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo
        - pip3 install .

    - os: linux
      language: python
      python: 3.7
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo
        - pip3 install .

    - os: linux
      language: python
      python: 3.8
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo
        - pip3 install .

      # MacOS (OSX) Jobs
    - os: osx
      language: sh
      python: 3.6
      env: PYVER="3.6.10"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo
        - pip3 install .

    - os: osx
      language: sh
      python: 3.7
      env: PYVER="3.7.7"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo
        - pip3 install .

    - os: osx
      language: sh
      python: 3.8
      env: PYVER="3.8.0"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo
        - pip3 install .

      # Windows Jobs
    - os: windows
      language: sh
      python: 3.6
      # the latest version available on chocolatey is 3.6.8
      env: PYVER="3.6.8" PYDIR="Python36"
      install:
        - choco install python --version=$PYVER
        - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --upgrade pip
        - python -m pip install --user -r ./.travis/travis-requirements.txt
        - python ./.travis/cairo-windows.py
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --user .

    - os: windows
      language: sh
      python: 3.7
      env: PYVER="3.7.7" PYDIR="Python37"
      install:
        - choco install python --version=$PYVER
        - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --upgrade pip
        - python -m pip install --user -r ./.travis/travis-requirements.txt
        - python ./.travis/cairo-windows.py
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --user .

    - os: windows
      language: sh
      python: 3.8
      env: PYVER="3.8.0" PYDIR="Python38"
      install:
        - choco install python --version=$PYVER
        - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --upgrade pip
        - python -m pip install --user -r ./.travis/travis-requirements.txt
        - python ./.travis/cairo-windows.py
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --user .

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod +x ./.travis/osx.sh; sh ./.travis/osx.sh; fi

script:
  - pytest

branches:
  only:
  - travis-setup

notifications:
  email: false